version: '3.8'

services:
  # フロントエンド (Webアプリ)
  ocr-app:
    # Dockerfileからビルドするのではなく、既存のNginxイメージを直接使用します
    image: nginx:1.27-alpine-slim
    # ローカルのfrontendフォルダを、Nginxコンテナの公開ディレクトリに接続します
    volumes:
      - ./frontend:/usr/share/nginx/html
    container_name: ocr_webapp_frontend
    restart: always

  # バックエンド (PaddleOCR API)
  api-server:
    build:
      context: ./backend # backendフォルダのDockerfileを使ってビルドします
    container_name: ocr_api_backend
    restart: always

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ocr_cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token <ここにあなたのトークンを貼り付け>

# コンテナ同士が通信するためのネットワークを定義
networks:
  default:
    name: ocr_network