async function runCustomOCR(canvasElement) {
    console.log("バックエンドAPIに画像を送信します。");

    // Canvasから画像データをBlobとして取得
    const blob = await new Promise(resolve => canvasElement.toBlob(resolve, 'image/png'));

    // FormDataオブジェクトを作成して画像を追加
    const formData = new FormData();
    formData.append('image', blob, 'scan.png');

    try {
        // バックエンドの/ocrエンドポイントにPOSTリクエストを送信
        const response = await fetch('/api/ocr', {
            method: 'POST',
            body: formData,
        });

        if (!response.ok) {
            throw new Error(`APIエラー: ${response.statusText}`);
        }

        const result = await response.json();
        return result.text || "テキストが見つかりませんでした。";

    } catch (error) {
        console.error("APIへのリクエスト中にエラーが発生:", error);
        return "OCR処理中にエラーが発生しました。\nサーバーに接続できませんでした。";
    }
}