version: '3.8'

services:
  # フロントエンド (Webアプリ)
  ocr-app:
    build:
      context: ./frontend  # frontendフォルダのDockerfile(なければNginxなど)を使う
    image: nginx:1.27-alpine-slim # フロントエンドはNginxで配信
    volumes:
      - ./frontend:/usr/share/nginx/html # コードをマウント
    container_name: ocr_webapp_frontend
    restart: always

  # バックエンド (PaddleOCR API)
  api-server:
    build:
      context: ./backend # backendフォルダのDockerfileを使う
    container_name: ocr_api_backend
    restart: always

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ocr_cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token <ここにあなたのトークンを貼り付け>

networks:
  default:
    name: ocr_network